branch-defaults:
  master:
    environment: react-boilerplate-$CIRCLE_BRANCH
global:
  application_name: React Boilerplate
  # default_ec2_keyname: XXXXXX
  default_platform: Node.js 8.12
  default_region: us-west-1
  sc: git
