branch-defaults:
  docker:
    environment: react-boilerplate-docker-master
  master:
    environment: react-boilerplate-$CIRCLE_BRANCH
global:
  application_name: React Boilerplate
  default_platform: arn:aws:elasticbeanstalk:us-east-2::platform/Docker running on
    64bit Amazon Linux/2.12.2
  default_region: us-east-2
  sc: git
