version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.12
    working_directory: ~/react-boilerplate
    steps:
      - checkout
      - run:
          name: Installing
          command: |
            npm install
            npm install -g aws-sdk
      # - run:
      #     name: Testing
      #     command: npm run test
      - run:
          name: Deploying
          command: aws elasticbeanstalk deploy react-boilerplate-$CIRCLE_BRANCH
